spring.application.name=Backend
# spring.security.user.password=1234
# spring.security.user.name=user

# <<<<<<< HEAD

# =======
# security.ignored=/**
# >>>>>>> 5c9a54f280da59991047d45c394e017fdc2a5b52

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3307/spoffice
spring.datasource.username=root
spring.datasource.password=root
# spring.datasource.password=Raut@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
